name: dartway_serverpod_chat_server
description: Starting point for a Serverpod module.

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  serverpod: 2.9.1

  dartway_serverpod_core_server:
    git:
      url: https://github.com/dartway/dartway_serverpod_core.git
      ref: master
      path: dartway_serverpod_core_server

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.1

# dependency_overrides:
#   dartway_serverpod_core_server:
#     path: ../../dartway_serverpod_core/dartway_serverpod_core_server
#   dartway_serverpod_core_shared:
#     path: ../../dartway_serverpod_core/dartway_serverpod_core_shared