name: dartway_serverpod_core_shared
description: Shared constants, enums, and models for DartWay Core (used by both flutter app and server).
version: 1.0.0

environment:
  sdk: ^3.6.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  http: ^1.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
