name: dartway_serverpod_chat_client
description: Starting point for a Serverpod module client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  serverpod_client: 2.9.1
  dartway_serverpod_core_client:
    git:
      url: https://github.com/dartway/dartway.git
      ref: master
      path: packages/dartway_serverpod_core_client
