name: project_name_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_client: 2.9.1

  dartway_serverpod_core_client:
    git:
      url: https://github.com/dartway/dartway_serverpod_core.git
      ref: master
      path: dartway_serverpod_core_client